// Timer
export const START_TIMER = 'START_TIMER';
export const PAUSE_TIMER = 'PAUSE_TIMER';
export const RESUME_TIMER = 'RESUME_TIMER';

// Levels
export const RESET_LEVELS = 'RESET_LEVELS';
export const EDIT_DURATION = 'EDIT_DURATION';
export const EDIT_BIG_BLIND = 'EDIT_BIG_BLIND';
export const EDIT_SMALL_BLIND = 'EDIT_SMALL_BLIND';
export const REMOVE_LEVEL = 'REMOVE_LEVEL';
export const ADD_LEVEL = 'ADD_LEVEL';
export const ADD_BREAK = 'ADD_BREAK';
export const INCREMENT_CURRENT_LEVEL = 'INCREMENT_CURRENT_LEVEL';
export const DECREMENT_CURRENT_LEVEL = 'DECREMENT_CURRENT_LEVEL';
